---
# tasks file for openfire
- name: Get Openfire
  get_url:
    url: "http://www.igniterealtime.org/downloadServlet?filename=openfire/openfire_{{ openfire_version }}_all.deb"
    dest: "/tmp/openfire_{{ openfire_version }}.deb"

- name: Install java 7
  apt:
    update_cache: yes
    name: openjdk-7-jre

- name: Install Openfire
  apt:
    deb: "/tmp/openfire_{{ openfire_version }}.deb"
    dpkg_opts: force-confdef,force-confold
